---
- name: Install prerequisites so apt can use a repo over HTTPS
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

# I'd love to do this, but the GPG key we're interested in expired in
# December of 2023 and therefore fails to import.
# - name: Get mongodb-org GPG key
#   ansible.builtin.apt_key:
#     id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
#     keyserver: keyserver.ubuntu.com

# TODO - Since the repo GPG key is expired, instead of trusting the
# package repo we should instead download the package and store it in
# S3.  This avoids the attack vector whereby a nefarious agent swaps
# out the package at https://repo.mongodb.org/apt/debian for a
# compromised one.  See #26 for more details.
- name: Add Apt package repo for mongodb-org (official MongoDB package repo)
  ansible.builtin.apt_repository:
    filename: mongodb
    repo: >
      deb [trusted=yes] https://repo.mongodb.org/apt/debian
      stretch/mongodb-org/{{ version }} main

- name: Install mongo
  ansible.builtin.package:
    name: mongodb-org

- name: >-
    Ensure that the directory where the mongod drop-in will live
    actually exists
  ansible.builtin.file:
    group: root
    mode: u=rwx,g=rx,o=rx
    owner: root
    path: "{{ mongo_dropin_unit_file | dirname }}"
    state: directory

- name: Create the drop-in unit file
  ansible.builtin.copy:
    dest: "{{ mongo_dropin_unit_file }}"
    group: root
    mode: u=rw,g=r,o=r
    owner: root
    src: mongod.service
    # It would be great to use systemd-analyze verify here, but that
    # won't work.  See, for instance, this GitHub issue comment:
    # https://github.com/ansible/ansible/issues/19243#issuecomment-266508074
    # validate: /usr/bin/systemd-analyze verify %s

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable mongo
  ansible.builtin.service:
    enabled: true
    name: mongod

# pymongo is needed for the mongodb_user Ansible module
- name: Install pymongo via pip2 and pip3
  ansible.builtin.pip:
    executable: "{{ item }}"
    name: pymongo
  loop:
    - /usr/bin/pip2
    - /usr/bin/pip3
